---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint -c .ansible-lint
platforms:
  - name: instance
    image: rockylinux:8
    pre_build_image: true
    groups:
      - server
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        rsyslog_packages:
          - rsyslog
verifier:
  name: ansible
